name: trestle
author: Emil Persson <emil.n.persson@gmail.com>
homepage: https://github.com/dart-bridge/trestle
version: 0.10.0
environment:
  sdk: '>=1.12.0 <2.0.0'
description: Database gateway and ORM
dependencies:
  sqljocky: '^0.14.0'
  postgresql: '^0.3.0'
  sqlite: '^0.4.0'
dev_dependencies:
  test: any
